### ISSUE TITLE
Terrible Chest Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [eideehi/TerribleChest#1]
`Minecraft v1.14.4`
`Forge v28.1.96`
`Terrible Chest v7`

- Currently, if the chest is placed underwater, it will render with water flowing down it's sides.
- If Quark is installed, pg #s will overlap the Quark buttons

**Comment by eideehi** [comment]
Thank you for your report. It has been fixed in the 1.14.4-8.
