### ISSUE TITLE
[1.12.2]The chest disconnects itself from linking devices every time when entered the world

### ISSUE THREAD

**Issue by ChromaPIE** [eideehi/TerribleChest#7]
**Tested with the item ducts from Thermal Dynamics:** The duct shows no link to the chest, back to normal when removing the chest and then place it back.

**Tested with the storage bus from AE2:** Everything looks just as they always be, but in fact, judging from the terminal showing nothing in its GUI, the storage bus is unable to read what are inside the chest, back to normal when removing the chest and then place it back.

**Comment by eideehi** [comment]
Sorry, but we don't have the time or energy to support 1.12.2 any longer. I don't know if this will fix the problem, but please try 1.12.2-8, the last version of 1.12.2.

**Comment by ChromaPIE** [comment]
Fully understand. BUT I just have to report a problem in 1.12.2 because it's so simple yet so fatal: breaking the emerald tchest would instantly duplicate-drop it to the world, one with NBT tag and one without. This undoubtedly made the wonderful mod defective. Begging for a fix if you got time. However I totally understand it if you have already decided to completely terminate the maintenance of its 1.12.2 version, then I may turn to third-party fixes like DupeFix Project.
